/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMMAND_ACK PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        Command results.
      
*/
public class dlink_msg_command_ack extends DLinkMessage{

    public static final int DLINK_MSG_ID_COMMAND_ACK = 51;
    public static final int DLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = DLINK_MSG_ID_COMMAND_ACK;


      
    /**
    * Command ID (of acknowledged command).
    */
    public int command;
      
    /**
    * Result of command.
    */
    public short result;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_COMMAND_ACK;
              
        packet.payload.putUnsignedShort(command);
              
        packet.payload.putUnsignedByte(result);
        
        return packet;
    }

    /**
    * Decode a command_ack message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.command = payload.getUnsignedShort();
              
        this.result = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_command_ack(){
        msgid = DLINK_MSG_ID_COMMAND_ACK;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_command_ack(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_COMMAND_ACK;
        unpack(dLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_COMMAND_ACK - sysid:"+sysid+" compid:"+compid+" command:"+command+" result:"+result+"";
    }
}
        