/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE MISSION_REQUEST PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* Request the information of the mission item with the sequence number seq. The response of the system to this message should be a MISSION_ITEM message.
*/
public class dlink_msg_mission_request extends DLinkMessage{

    public static final int DLINK_MSG_ID_MISSION_REQUEST = 101;
    public static final int DLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = DLINK_MSG_ID_MISSION_REQUEST;


      
    /**
    * Sequence
    */
    public short seq;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_MISSION_REQUEST;
              
        packet.payload.putUnsignedByte(seq);
        
        return packet;
    }

    /**
    * Decode a mission_request message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.seq = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_mission_request(){
        msgid = DLINK_MSG_ID_MISSION_REQUEST;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_mission_request(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_MISSION_REQUEST;
        unpack(dLinkPacket.payload);        
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_MISSION_REQUEST - sysid:"+sysid+" compid:"+compid+" seq:"+seq+"";
    }
}
        