/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE DRONE_ATTITUDE PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        DJI drone attitude.
      
*/
public class dlink_msg_drone_attitude extends DLinkMessage{

    public static final int DLINK_MSG_ID_DRONE_ATTITUDE = 5;
    public static final int DLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = DLINK_MSG_ID_DRONE_ATTITUDE;


      
    /**
    * Roll angle (-pi..+pi)
    */
    public float roll;
      
    /**
    * Pitch angle (-pi..+pi)
    */
    public float pitch;
      
    /**
    * Yaw angle (-pi..+pi)
    */
    public float yaw;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_DRONE_ATTITUDE;
              
        packet.payload.putFloat(roll);
              
        packet.payload.putFloat(pitch);
              
        packet.payload.putFloat(yaw);
        
        return packet;
    }

    /**
    * Decode a drone_attitude message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.roll = payload.getFloat();
              
        this.pitch = payload.getFloat();
              
        this.yaw = payload.getFloat();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_drone_attitude(){
        msgid = DLINK_MSG_ID_DRONE_ATTITUDE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_drone_attitude(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_DRONE_ATTITUDE;
        unpack(dLinkPacket.payload);        
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_DRONE_ATTITUDE - sysid:"+sysid+" compid:"+compid+" roll:"+roll+" pitch:"+pitch+" yaw:"+yaw+"";
    }
}
        