/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE HEARTBEAT PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        The heartbeat message shows that a system is present and respoding.
      
*/
public class dlink_msg_heartbeat extends DLinkMessage{

    public static final int DLINK_MSG_ID_HEARTBEAT = 0;
    public static final int DLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = DLINK_MSG_ID_HEARTBEAT;


      
    /**
    * Product model.
    */
    public short product_model;
      
    /**
    * System status
    */
    public short system_status;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_HEARTBEAT;
              
        packet.payload.putUnsignedByte(product_model);
              
        packet.payload.putUnsignedByte(system_status);
        
        return packet;
    }

    /**
    * Decode a heartbeat message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.product_model = payload.getUnsignedByte();
              
        this.system_status = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_heartbeat(){
        msgid = DLINK_MSG_ID_HEARTBEAT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_heartbeat(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_HEARTBEAT;
        unpack(dLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_HEARTBEAT - sysid:"+sysid+" compid:"+compid+" product_model:"+product_model+" system_status:"+system_status+"";
    }
}
        