/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE DRONE_STATUS PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        DJI drone status.
      
*/
public class dlink_msg_drone_status extends DLinkMessage{

    public static final int DLINK_MSG_ID_DRONE_STATUS = 6;
    public static final int DLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = DLINK_MSG_ID_DRONE_STATUS;


      
    /**
    * Armed
    */
    public short armed;
      
    /**
    * Warning
    */
    public short warning;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_DRONE_STATUS;
              
        packet.payload.putUnsignedByte(armed);
              
        packet.payload.putUnsignedByte(warning);
        
        return packet;
    }

    /**
    * Decode a drone_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.armed = payload.getUnsignedByte();
              
        this.warning = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_drone_status(){
        msgid = DLINK_MSG_ID_DRONE_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_drone_status(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_DRONE_STATUS;
        unpack(dLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_DRONE_STATUS - sysid:"+sysid+" compid:"+compid+" armed:"+armed+" warning:"+warning+"";
    }
}
        