/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE DRONE_GLOBAL_POSITION PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        Drone global postion.
      
*/
public class dlink_msg_drone_global_position extends DLinkMessage{

    public static final int DLINK_MSG_ID_DRONE_GLOBAL_POSITION = 4;
    public static final int DLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = DLINK_MSG_ID_DRONE_GLOBAL_POSITION;


      
    /**
    * Latitude, expressed
    */
    public int lat;
      
    /**
    * Longitude, expressed
    */
    public int lon;
      
    /**
    * Altitude (MSL). Note that virtually all GPS modules provide both WGS84 and MSL.
    */
    public int alt;
      
    /**
    * Altitude above ground
    */
    public int relative_alt;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_DRONE_GLOBAL_POSITION;
              
        packet.payload.putInt(lat);
              
        packet.payload.putInt(lon);
              
        packet.payload.putInt(alt);
              
        packet.payload.putInt(relative_alt);
        
        return packet;
    }

    /**
    * Decode a drone_global_position message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.lat = payload.getInt();
              
        this.lon = payload.getInt();
              
        this.alt = payload.getInt();
              
        this.relative_alt = payload.getInt();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_drone_global_position(){
        msgid = DLINK_MSG_ID_DRONE_GLOBAL_POSITION;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_drone_global_position(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_DRONE_GLOBAL_POSITION;
        unpack(dLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_DRONE_GLOBAL_POSITION - sysid:"+sysid+" compid:"+compid+" lat:"+lat+" lon:"+lon+" alt:"+alt+" relative_alt:"+relative_alt+"";
    }
}
        