/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE DRONE_BATTERY_STATUS PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        DJI drone battery status.
      
*/
public class dlink_msg_drone_battery_status extends DLinkMessage{

    public static final int DLINK_MSG_ID_DRONE_BATTERY_STATUS = 3;
    public static final int DLINK_MSG_LENGTH = 13;
    private static final long serialVersionUID = DLINK_MSG_ID_DRONE_BATTERY_STATUS;


      
    /**
    * mAh
    */
    public long mAh;
      
    /**
    * Voltage
    */
    public long voltage;
      
    /**
    * Current
    */
    public long current;
      
    /**
    * Percent
    */
    public short percent;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_DRONE_BATTERY_STATUS;
              
        packet.payload.putUnsignedInt(mAh);
              
        packet.payload.putUnsignedInt(voltage);
              
        packet.payload.putUnsignedInt(current);
              
        packet.payload.putUnsignedByte(percent);
        
        return packet;
    }

    /**
    * Decode a drone_battery_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.mAh = payload.getUnsignedInt();
              
        this.voltage = payload.getUnsignedInt();
              
        this.current = payload.getUnsignedInt();
              
        this.percent = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_drone_battery_status(){
        msgid = DLINK_MSG_ID_DRONE_BATTERY_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_drone_battery_status(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_DRONE_BATTERY_STATUS;
        unpack(dLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_DRONE_BATTERY_STATUS - sysid:"+sysid+" compid:"+compid+" mAh:"+mAh+" voltage:"+voltage+" current:"+current+" percent:"+percent+"";
    }
}
        