/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMMAND_SHORT PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        Send a command message without a param.
      
*/
public class dlink_msg_command_short extends DLinkMessage{

    public static final int DLINK_MSG_ID_COMMAND_SHORT = 50;
    public static final int DLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = DLINK_MSG_ID_COMMAND_SHORT;


      
    /**
    * Command ID (of command to send).
    */
    public int command;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_COMMAND_SHORT;
              
        packet.payload.putUnsignedShort(command);
        
        return packet;
    }

    /**
    * Decode a command_short message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.command = payload.getUnsignedShort();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_command_short(){
        msgid = DLINK_MSG_ID_COMMAND_SHORT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_command_short(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_COMMAND_SHORT;
        unpack(dLinkPacket.payload);        
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_COMMAND_SHORT - sysid:"+sysid+" compid:"+compid+" command:"+command+"";
    }
}
        