/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

// MESSAGE CHARGE_PAD_STATUS PACKING
package com.DLink.messages;
import com.DLink.DLinkPacket;
import com.DLink.DLinkMessage;
import com.DLink.DLinkPayload;
        
/**
* 
        Heisha charge pad status.
      
*/
public class dlink_msg_charge_pad_status extends DLinkMessage{

    public static final int DLINK_MSG_ID_CHARGE_PAD_STATUS = 1;
    public static final int DLINK_MSG_LENGTH = 10;
    private static final long serialVersionUID = DLINK_MSG_ID_CHARGE_PAD_STATUS;


      
    /**
    * 
      
    */
    public long charge_voltage;
      
    /**
    * 
      
    */
    public long charge_current;
      
    /**
    * 
      
    */
    public short bar_position;
      
    /**
    * 
      
    */
    public short charge_status;
    

    /**
    * Generates the payload for a dlink message for a message of this type
    * @return
    */
    public DLinkPacket pack(){
        DLinkPacket packet = new DLinkPacket(DLINK_MSG_LENGTH);
        packet.sysid = 0;
        packet.compid = 0;
        packet.msgid = DLINK_MSG_ID_CHARGE_PAD_STATUS;
              
        packet.payload.putUnsignedInt(charge_voltage);
              
        packet.payload.putUnsignedInt(charge_current);
              
        packet.payload.putUnsignedByte(bar_position);
              
        packet.payload.putUnsignedByte(charge_status);
        
        return packet;
    }

    /**
    * Decode a charge_pad_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(DLinkPayload payload) {
        payload.resetIndex();
              
        this.charge_voltage = payload.getUnsignedInt();
              
        this.charge_current = payload.getUnsignedInt();
              
        this.bar_position = payload.getUnsignedByte();
              
        this.charge_status = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public dlink_msg_charge_pad_status(){
        msgid = DLINK_MSG_ID_CHARGE_PAD_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a dlink packet
    *
    */
    public dlink_msg_charge_pad_status(DLinkPacket dLinkPacket){
        this.sysid = dLinkPacket.sysid;
        this.compid = dLinkPacket.compid;
        this.msgid = DLINK_MSG_ID_CHARGE_PAD_STATUS;
        unpack(dLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "DLINK_MSG_ID_CHARGE_PAD_STATUS - sysid:"+sysid+" compid:"+compid+" charge_voltage:"+charge_voltage+" charge_current:"+charge_current+" bar_position:"+bar_position+" charge_status:"+charge_status+"";
    }
}
        