/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

package com.DLink.enums;

/** 
* 
*/
public class CHARGE_PAD_BAR_POSITION {
   public static final int CHARGE_PAD_BAR_POSITION_UNKNOWN = 0; /*  | */
   public static final int CHARGE_PAD_BAR_POSITION_LOCKED = 1; /*  | */
   public static final int CHARGE_PAD_BAR_POSITION_UNLOCKED = 2; /*  | */
   public static final int CHARGE_PAD_BAR_POSITION_ENUM_END = 3; /*  | */
}
            