/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

package com.DLink.enums;

/** 
* 
*/
public class CMD_ID {
   public static final int CHARGE_PAD_LOCK = 0; /*  | */
   public static final int CHARGE_PAD_UNLOCK = 1; /*  | */
   public static final int CHARGE_PAD_CHARGE = 2; /*  | */
   public static final int CHARGE_PAD_TURN_ON_OFF_RC = 3; /*  | */
   public static final int CHARGE_PAD_TURN_ON_OFF_DRONE = 4; /*  | */
   public static final int DRONE_TAKEOFF = 100; /*  | */
   public static final int CMD_ID_ENUM_END = 101; /*  | */
}
            