/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

package com.DLink.enums;

/** 
* 
*/
public class COMPONENT {
   public static final int DJI_COMPONENT_RC = 1; /*  | */
   public static final int DJI_COMPONENT_FC = 2; /*  | */
   public static final int DJI_COMPONENT_BAT = 4; /*  | */
   public static final int DJI_COMPONENT_GIMBAL = 8; /*  | */
   public static final int DJI_COMPONENT_CAMERA = 16; /*  | */
   public static final int COMPONENT_ENUM_END = 17; /*  | */
}
            