/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java dlink generator tool. It should not be modified by hand.
 */

package com.DLink.enums;

/** 
* 
*/
public class HEISHA_PRODUCT_MODEL {
   public static final int UNKNOWN = 0; /*  | */
   public static final int C300M2 = 1; /*  | */
   public static final int HEISHA_PRODUCT_MODEL_ENUM_END = 2; /*  | */
}
            